spring.application.name=spring_web_MVC

# for Greetings App

# server port (optional)
#server.port=8080

# jsp view resolver
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp


# for Course App
server.port=8080
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp