spring.application.name=spring_web_MVC

# 1 . for Greetings App

# server port (optional)
#server.port=8080

# jsp view resolver
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp


# 2 . for Course App
# server.port=8080
# spring.mvc.view.prefix=/WEB-INF/views/
# spring.mvc.view.suffix=.jsp


# 3 . for Query Param App
server.port=8080
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
